const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context=vm.createContext({});
vm.runInContext(fs.readFileSync(__dirname+'/study-model.js','utf8')+'\nthis.model=StudyModel;',context);
const model=context.model;
let sequence=0;
const post=(role,kind,text='Mensagem',extra={})=>({id:'p'+(++sequence),role,kind,text,authorId:role==='teacher'?'teacher':'lia',createdAt:new Date(2026,8,19,10,sequence).toISOString(),...extra});
const thread={id:'thread-a',title:'Cilindro',studentId:'lia',classId:'aurora',assignmentId:'task',stepId:'step',status:'process',posts:[]};
model.addPost(thread,post('student','help','Estou preso nisso.'));
assert.equal(thread.status,'help');assert.equal(model.needsTeacher(thread),true);
model.addPost(thread,post('teacher','message','Observe este plano.'));
assert.equal(thread.status,'process');assert.equal(model.needsTeacher(thread),false);
assert.equal(model.unread(thread,'lia',{'lia|thread-a':1}),1);
model.addPost(thread,post('student','process','Segue o processo.',{deliveryId:'image1'}));
assert.equal(thread.status,'process');assert.equal(model.needsTeacher(thread),true);
model.addPost(thread,post('student','submit','Pronto para avaliar.',{deliveryId:'image2'}));
assert.equal(thread.status,'submitted');
model.addPost(thread,post('teacher','guidance','Tente separar os planos.'));
assert.equal(thread.status,'revision');
model.addPost(thread,post('student','process','Nova tentativa.',{deliveryId:'image3'}));
assert.equal(thread.status,'process');
model.addPost(thread,post('teacher','complete','Agora os planos estão claros.'));
assert.equal(thread.status,'complete');assert.equal(model.needsTeacher(thread),false);
assert.equal(thread.posts.length,7);
assert.throws(()=>model.addPost(thread,post('student','process','')));
const deliveries=[1,2,3].map(version=>({id:'image'+version,rootId:'thread-a',version,studentId:'lia',classId:'aurora',assignmentId:'task',stepId:'step',title:'Cilindro',date:'2026-09-19T12:00:00Z',review:version===3?{status:'approved',feedback:'Concluído.',date:'2026-09-19T13:00:00Z'}:null}));
const migrated=model.migrate(deliveries);
assert.equal(migrated.length,1);assert.equal(migrated[0].posts.length,4);assert.equal(migrated[0].status,'complete');
const data={version:2,threads:[thread],seen:{},drafts:{},locations:{},roomMessages:{},publications:{},boards:{},liveLessons:{}};
const school={students:[{id:'lia',classId:'aurora'}],assignments:[{id:'task',classId:'aurora',steps:[{id:'step'}]}]};
assert.equal(model.validate(JSON.parse(JSON.stringify(data)),school,deliveries).threads[0].posts.length,7);
const wrong=JSON.parse(JSON.stringify(deliveries));wrong[0].studentId='pedro';
assert.throws(()=>model.validate(data,school,wrong));
const badDraft=JSON.parse(JSON.stringify(data));badDraft.drafts.x={image:'https://example.com/private.png'};
assert.throws(()=>model.validate(badDraft,school,deliveries));
const foreignPublication=JSON.parse(JSON.stringify(data));foreignPublication.publications['thread-a']='missing-image';
assert.throws(()=>model.validate(foreignPublication,school,deliveries));
console.log('PASS: ajuda imediata, resposta sem nota, processo, entrega explícita, revisão, conclusão, não lidas, versões agrupadas, cópia e rejeição de vínculos inválidos.');
