(() => {
  'use strict';
  const games = [
    {name:'Gira na Cabeça',weeks:'6 e 10 · Rotação de formas',task:'Imagine este conjunto de blocos girando 90° para a direita. Use o controle para conferir o movimento.',control:'Girar objeto',range:[0,90,0],unit:'°',caption:'O mesmo objeto, outro ponto de vista',play:'O aluno observa uma forma, tenta reconhecer sua vista depois de uma rotação e escolhe entre alternativas. Mais adiante, pode desenhar a vista antes de conferir.',feedback:'A rotação animada acompanha o mesmo bloco colorido. Isso ajuda a perceber qual parte virou para frente e qual ficou escondida.',analysis:'Acompanhe o bloco vermelho: ele serve de referência para reconhecer o objeto. Girar muda a vista, mas mantém as relações entre os blocos. Experimente chegar aos 90° e voltar.',scope:'Criar uma biblioteca de formas e alternativas com erros plausíveis. A primeira versão pode ser só de reconhecimento; avaliar desenhos fica para depois.'},
    {name:'Oficina de Interseções',weeks:'4 e 8 · Cortes e fusão',task:'Um plano corta um cilindro. Você espera uma seção circular ou elíptica? Compare os dois cortes.',options:['Corte perpendicular','Corte inclinado'],caption:'Seção de um cilindro circular',play:'Antes de revelar, o aluno prevê o contorno do corte. Começa com planos e sólidos simples; depois passa para encontros entre dois sólidos.',feedback:'O corte aparece sobre a forma e também visto de frente. Assim, a elipse que vemos em perspectiva não é confundida com o formato real da seção.',analysis:'No corte perpendicular ao eixo, a seção é um círculo — mesmo que pareça uma elipse na vista em perspectiva. No corte oblíquo mostrado aqui, a seção é uma elipse. Os dois desenhos à direita representam a seção vista de frente.',scope:'Modelos 3D e cortes calculados, com câmera que possa girar. Esta amostra usa dois diagramas preparados; não calcula interseções livres.'},
    {name:'De Onde Vem a Luz?',weeks:'9 · Luz, sombra e valores',task:'Mova a luz de um lado para o outro e observe a direção da sombra de um objeto sobre o chão.',control:'Posição da luz',range:[-150,150,-110],unit:'',caption:'Uma luz pontual e um objeto opaco',play:'O aluno recebe uma fonte de luz e posiciona a sombra antes de conferir. Outra rodada pode pedir que distribua três valores nas faces de um cubo.',feedback:'Raios de luz explicam os limites da sombra. O professor diferencia sombra própria, sombra projetada e o papel do plano que recebe a luz.',analysis:'A sombra se projeta no lado oposto à luz. Os raios azuis passam pelas extremidades do objeto e continuam até o chão. A cor chapada é apenas uma simplificação: esta demonstração não simula penumbra nem iluminação realista.',scope:'Exercícios separados de direção da sombra e valores nas faces. Para começar, bastam poucas situações calculadas, sem um renderizador completo.'},
    {name:'Raio-X de Objetos',weeks:'10 e 14–16 · Sketch dinâmico',task:'Qual conjunto de volumes explica melhor este carrinho? Alterne entre uma blocagem útil e uma simplificação que esconde sua estrutura.',options:['Caixas e cilindros','Uma massa única'],caption:'Referência desenhada para esta demonstração',play:'Sobre uma referência, o aluno posiciona e ajusta alguns volumes simples. O objetivo é explicar a estrutura, sem copiar os detalhes.',feedback:'Uma blocagem comentada mostra orientação, tamanho relativo e encaixes. Podem existir várias soluções válidas; não precisa coincidir com um único desenho.',analysis:'Uma caixa maior organiza a carroceria, outra organiza a cabine e cilindros explicam as rodas. Uma massa única ajuda a medir o tamanho geral, mas não explica o encaixe das partes. A sobreposição azul é uma leitura possível, não um gabarito único.',scope:'Ferramentas para mover, girar e dimensionar volumes, mais referências autorizadas e análises do professor. Aqui a comparação já vem montada.'},
    {name:'Hachura que Abraça',weeks:'20–21 · Volume e textura',task:'Compare traços retos com traços que contornam o cilindro. O que cada direção faz você perceber?',options:['Traços retos','Contornar o volume'],caption:'Estudo de contorno transversal',play:'O aluno recebe uma superfície e desenha poucas linhas acompanhando seu volume. Depois pode variar espaçamento e densidade para estudar valor e textura.',feedback:'Uma sobreposição compara a curvatura dos traços e o volume sugerido. A direção é discutida em relação ao objetivo do estudo, sem tratar toda hachura reta como erro.',analysis:'Neste exercício de contorno, a curva sugere que a linha passa ao redor do cilindro. Hachuras retas também podem funcionar para representar valores: aqui estamos isolando a direção que descreve o volume.',scope:'Uma prancheta de desenho e exemplos comentados por superfície. Evitar dar uma nota automática para qualquer estilo de hachura.'},
    {name:'Laboratório de Silhuetas',weeks:'22–24 · Ritmo e linguagem das formas',task:'O objetivo é criar uma criatura que pareça pesada. Compare três distribuições de massa em miniatura.',options:['Pesada','Ágil','Ameaçadora'],caption:'Uma intenção, diferentes escolhas de forma',play:'O aluno combina massas simples e produz três silhuetas para uma intenção. A miniatura ajuda a conferir a leitura antes de desenhar detalhes.',feedback:'A comparação destaca base de apoio, proporção e espaços negativos. Professor e turma discutem o que a silhueta comunica, sem uma resposta única.',analysis:'A versão pesada concentra massa no corpo e tem uma base larga. A ágil alonga apoios e cria mais espaços vazios. A ameaçadora usa pontas e uma postura elevada. São hipóteses de leitura; contexto e cultura também mudam a interpretação.',scope:'Editor simples de massas, salvar três variações e comparar lado a lado. O objetivo é justificar decisões, sem uma pontuação de criatividade.'},
    {name:'Diretor de Cena',weeks:'11, 25 e 30 · Composição e narrativa',task:'Queremos que a chave seja percebida primeiro. Compare três maneiras de organizar a mesma cena.',options:['Tudo compete','Contraste na chave','Mais espaço livre'],caption:'Objetivo narrativo: encontrar a chave',play:'O aluno recebe uma intenção narrativa e rearranja poucos objetos. Pode ajustar escala, enquadramento e contraste para conduzir o olhar.',feedback:'As versões são comparadas em miniatura. O aluno explica sua escolha e o professor comenta hierarquia, sobreposições e clareza da história.',analysis:'Quando tudo tem contraste parecido, a chave compete com o restante. Um fundo escuro a destaca pelo valor; mais espaço livre reduz a competição ao redor. Nenhum recurso garante sozinho a leitura: a comparação ajuda a testar a intenção.',scope:'Poucos objetos arrastáveis, controle de escala e de valores. Começar em 2D permite estudar composição sem construir um editor de cenários 3D.'},
    {name:'Gesto Essencial',weeks:'33–35 · Proporção, gesto e blocagem',task:'Qual linha acompanha melhor a ação da pose? Compare as leituras e revele a relação entre tórax e pelve.',options:['Linha vertical','Curva de ação'],caption:'Pose esquemática; análise ilustrativa',play:'O aluno observa uma pose e registra linha de ação, tórax e pelve com poucos traços. O tempo pode ser livre no início e limitado em treinos posteriores.',feedback:'A análise do professor destaca fluxo e inclinação das massas. O desenho do aluno continua visível para comparar a intenção, sem premiar copiar o contorno.',analysis:'Nesta pose, a curva conecta a inclinação do tronco à perna de apoio. Tórax e pelve têm inclinações diferentes. A linha de ação é uma síntese possível do movimento, não uma peça anatômica nem um único traço obrigatório.',scope:'Referências autorizadas, tela para poucos traços e uma análise preparada para cada pose. Cronômetro opcional; nada de reconhecimento automático de anatomia na primeira versão.'},
    {name:'Detetive das Dobras',weeks:'36 · Apoio e tensão do tecido',task:'O tecido está suspenso. Mude os pontos de apoio e preveja onde apareceriam as principais dobras.',options:['Dois apoios','Um apoio central'],caption:'Diagrama simplificado de tecido suspenso',play:'O aluno marca apoios e traça a direção provável de algumas dobras antes de revelar uma análise da referência.',feedback:'A explicação liga cada grupo de dobras ao apoio, à gravidade e à tensão. O professor comenta também o material e a folga do tecido.',analysis:'Dois apoios criam uma região pendente entre eles. Um apoio central organiza dobras que descem e se abrem a partir dessa região. O desenho é esquemático: rigidez, peso e quantidade de tecido alteram o resultado.',scope:'Fotos autorizadas com apoios e dobras anotados pelo professor. Não precisa de simulação física: a primeira versão pode trabalhar sobre referências fixas.'},
    {name:'Mapa do Corpo',weeks:'37–44 · Marcos anatômicos',task:'Localize a linha dos ombros ou a região da pelve nesta figura de frente. Escolha um mapa e confira a leitura.',options:['Ombros','Pelve'],caption:'Figura esquemática, sem escala anatômica de avaliação',play:'O aluno posiciona alguns marcos em uma referência. Começa com ajuda e passa para outras poses e vistas, relacionando pontos ao volume do corpo.',feedback:'A análise mostra regiões de referência e suas relações, com tolerância adequada à pose. Não reduz pessoas diferentes a uma proporção universal.',analysis:'Os pontos azuis mostram regiões de referência do exemplo. Nos ombros, procuramos os extremos ósseos relacionados ao acrômio; na pelve, referências anteriores como as espinhas ilíacas anterossuperiores. O contorno externo nem sempre mostra esses pontos com clareza.',scope:'Referências e marcações revisadas pelo professor, com vistas progressivas. Esta figura serve para explicar a mecânica; ainda não é material para avaliar anatomia.'}
  ];
  const $ = id => document.getElementById(id);
  let current = 0, value = 0, revealed = false;
  const line = (x1,y1,x2,y2,cls='') => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}"/>`;
  const path = (d,cls='shape',extra='') => `<path d="${d}" class="${cls}" ${extra}/>`;
  const text = (x,y,s,extra='') => `<text x="${x}" y="${y}" text-anchor="middle" ${extra}>${s}</text>`;
  const dot = (x,y,color='#de2246') => `<circle cx="${x}" cy="${y}" r="6" fill="${color}"/>`;
  function blocks(angle) {
    const a=angle*Math.PI/180+.48, ca=Math.cos(a),sa=Math.sin(a);
    const project=([x,y,z])=>[380+(x*ca-z*sa)*66,265+(x*sa+z*ca)*25-y*66];
    const cells=[[0,0,0],[1,0,0],[2,0,0],[0,1,0],[0,0,1]];
    const faces=[];
    cells.forEach(([x,y,z],i)=>{
      const p=[[x,y,z],[x+1,y,z],[x+1,y+1,z],[x,y+1,z],[x,y,z+1],[x+1,y,z+1],[x+1,y+1,z+1],[x,y+1,z+1]];
      [[0,1,2,3],[1,5,6,2],[5,4,7,6],[4,0,3,7],[3,2,6,7]].forEach((indices,j)=>{
        const coords=indices.map(k=>p[k]);
        faces.push({depth:coords.reduce((n,p)=>n+p[0]*sa+p[2]*ca,0)/4,points:coords.map(project).map(p=>p.join(',')).join(' '),fill:i===3?['#de2246','#f17b91','#a71c37','#c43b56','#ffa4b5'][j]:['#c8c4bf','#dedad4','#b4b0ab','#e9e5df','#f8f6f2'][j]});
      });
    });
    return faces.sort((a,b)=>a.depth-b.depth).map(f=>`<polygon points="${f.points}" fill="${f.fill}" stroke="#34343a" stroke-width="1.6"/>`).join('')+text(380,350,`Rotação: ${angle}° · alvo: 90°`);
  }
  const figure = () => `<g fill="none" stroke="#cbc5be" stroke-width="29" stroke-linecap="round" stroke-linejoin="round"><path d="M374 127 L353 195 L389 245 M360 162 L306 171 L271 129 M360 155 L428 179 L465 143 M387 249 L351 306 L293 329 M389 246 L427 287 L446 344"/></g><ellipse cx="385" cy="92" rx="25" ry="30" fill="#cbc5be" transform="rotate(20 385 92)"/>`;
  function scene() {
    let s='';
    switch(current){
      case 0:s=blocks(value);break;
      case 1:s=`<ellipse cx="255" cy="100" rx="95" ry="30" class="shape"/><path d="M160 100 V290 A95 30 0 0 0 350 290 V100" class="shape"/><ellipse cx="255" cy="100" rx="95" ry="30" class="shape"/><path d="${value?'M115 255 L300 145 L402 197 L220 312 Z':'M112 208 L283 166 L405 207 L229 253 Z'}" fill="#246eaf" fill-opacity=".12" stroke="#246eaf" stroke-width="2"/>${revealed?`<ellipse cx="255" cy="210" rx="95" ry="${value?55:30}" transform="rotate(${value?-25:0} 255 210)" class="mark"/><ellipse cx="570" cy="200" rx="${value?100:65}" ry="65" class="mark"/>${text(570,310,value?'Section elliptique':'Section circulaire')}`:text(570,205,'Quelle forme de section ?')}`.replace('Section elliptique','Seção elíptica').replace('Section circulaire','Seção circular').replace('Quelle forme de section ?','Como seria o corte de frente?');break;
      case 2:{const light=380+value,top=170,ground=305,ly=55;const end=x=>light+(x-light)*(ground-ly)/(top-ly);s=`<path d="M80 305 H690" stroke="#bbb4ad" stroke-width="2"/><path d="M${end(340)} 305 L${end(420)} 305" stroke="#89828c" stroke-width="14" stroke-linecap="round"/><rect x="340" y="170" width="80" height="135" class="shape"/><circle cx="${light}" cy="55" r="17" fill="#eab747"/>${text(light,26,'LUZ')}${revealed?line(light,55,end(340),305,'answer')+line(light,55,end(420),305,'answer'):''}${text(380,360,'Vista lateral · a sombra está no chão')}`;break;}
      case 3:s=`<g stroke="#8b8580" stroke-width="3" fill="#d8d3cb"><path d="M161 265 L180 205 L302 189 L346 134 L460 134 L513 190 L592 217 L602 270 Z"/><path d="M319 190 L355 145 L450 145 L492 190 Z" fill="#f5f3f0"/><circle cx="256" cy="266" r="42"/><circle cx="506" cy="266" r="42"/></g>${value===0?'<g fill="none" stroke="#de2246" stroke-width="3"><rect x="174" y="198" width="423" height="75"/><path d="M306 195 L345 126 H467 L521 195 Z"/><ellipse cx="256" cy="265" rx="44" ry="46"/><ellipse cx="506" cy="265" rx="44" ry="46"/></g>':'<ellipse cx="380" cy="215" rx="230" ry="91" class="mark"/>'}${revealed?'<g class="answer"><path d="M174 198 L208 180 H566 L597 198 M306 195 L330 181 L369 117 H487 L521 195 M256 219 L280 211 M256 311 L280 303 M506 219 L530 211 M506 311 L530 303"/></g>':''}`;break;
      case 4:s='<path d="M265 105 V292 A115 34 0 0 0 495 292 V105" class="shape"/><ellipse cx="380" cy="105" rx="115" ry="34" class="shape"/>';for(let y=145;y<=270;y+=25){s+=path(value?`M267 ${y} C300 ${y+48} 460 ${y+48} 493 ${y}`:`M267 ${y} H493`,'mark');if(revealed)s+=path(`M267 ${y} C300 ${y+48} 460 ${y+48} 493 ${y}`,'answer');}break;
      case 5:{const shapes=['M-105 40 Q-140-75-38-87 Q38-125 83-50 L129-24 L126 17 L90 25 L76 88 L29 88 L20 45 L-39 51 L-58 88 L-104 88 Z','M-112 0 Q-54-47 34-17 L82-70 L107-63 L73-10 L52 10 L94 69 L76 79 L15 30 L-27 22 L-87 77 L-110 70 L-61 14 L-138 26 Z','M-105 71 L-77 13 L-99-37 L-56-19 L-59-84 L-24-55 L0-114 L21-58 L65-93 L66-30 L111-42 L88 14 L113 71 L61 82 L45 30 L-44 30 L-58 82 Z'];s=shapes.map((d,i)=>`<g transform="translate(${160+i*220} 200) scale(${i===value?1:.74})"><path d="${d}" fill="${i===value?'#de2246':'#b6afa8'}"/></g>${text(160+i*220,335,['Pesada','Ágil','Ameaçadora'][i])}`).join('');if(revealed)s+=line(45+value*220,299,275+value*220,299,'answer');break;}
      case 6:{const keyX=value===2?470:380;s=`<rect x="95" y="65" width="570" height="260" fill="${value===1?'#343139':'#dfdbd5'}"/><path d="M95 266 H665" stroke="#b6aea4" stroke-width="2"/><g fill="${value===1?'#48424d':'#969087'}"><rect x="140" y="155" width="${value===2?80:170}" height="112"/><path d="M${value===2?225:490} 267 V178 Q${value===2?260:535} 100 ${value===2?295:580} 178 V267 Z"/><rect x="${value===2?180:359}" y="94" width="84" height="70"/></g><g stroke="${value===1?'#fff3cd':'#3c383b'}" stroke-width="9" fill="none" transform="translate(${keyX} 232)"><circle r="17"/><path d="M17 0 H65 M49 0 V15 M64 0 V15"/></g>${revealed?`<circle cx="${keyX+25}" cy="233" r="62" class="answer"/>`:''}`;break;}
      case 7:s=figure()+path(value?'M390 64 Q322 184 390 242 Q412 282 451 352':'M380 65 V350','mark');if(revealed)s+='<g class="answer"><ellipse cx="361" cy="166" rx="37" ry="49" transform="rotate(20 361 166)"/><ellipse cx="385" cy="240" rx="37" ry="25" transform="rotate(-15 385 240)"/></g>'+text(538,171,'Tórax')+text(538,246,'Pelve');break;
      case 8:s=path(value?'M380 78 Q295 130 245 292 Q380 341 520 292 Q460 129 380 78 Z':'M232 80 Q380 146 530 80 L565 300 Q380 359 205 300 Z');s+=value?dot(380,78):dot(232,80)+dot(530,80);if(revealed){s+=value?path('M380 87 Q320 190 287 305 M380 87 Q363 214 363 319 M380 87 Q403 204 425 316 M380 87 Q449 176 477 302','answer'):path('M238 87 Q375 215 522 87 M239 92 Q367 279 524 92 M237 98 Q350 340 527 98','answer');}s+=text(380,375,'Pontos vermelhos = apoios do tecido');break;
      case 9:s='<g fill="#d1cbc3" stroke="#aaa29a" stroke-width="2"><ellipse cx="380" cy="70" rx="26" ry="33"/><path d="M365 101 L331 119 L298 221 L318 230 L342 169 L348 229 L336 269 L343 367 H367 L380 282 L393 367 H417 L424 269 L412 229 L418 169 L442 230 L462 221 L429 119 L395 101 Z"/></g>';if(revealed){const y=value?242:123,x=value?350:334;s+=dot(x,y,'#246eaf')+dot(760-x,y,'#246eaf')+line(x,y,760-x,y,'answer')+text(557,y+5,value?'Referências da pelve':'Referências dos ombros');}else s+=text(563,193,value?'Localize a pelve':'Localize os ombros');break;
    }
    $('scene').innerHTML=s;
    $('scene').setAttribute('aria-label',games[current].name+'. '+games[current].caption+(revealed?'. Explicação visual revelada.':''));
  }
  function render(){
    const game=games[current];
    $('week').textContent='SEMANAS '+game.weeks;
    ['title','task','play','feedback','scope'].forEach(id=>$(id).textContent=id==='title'?game.name:game[id]);
    $('scene-caption').textContent=game.caption;
    $('count').textContent=String(current+1).padStart(2,'0')+' / 10';
    $('next').textContent=current===9?'Voltar à primeira →':'Próxima ideia →';
    $('analysis').innerHTML='<strong>O que observar</strong><br>'+game.analysis;
    $('analysis').hidden=!revealed;
    $('reveal').textContent=revealed?'Ocultar explicação':'Revelar explicação';
    $('reveal').setAttribute('aria-expanded',String(revealed));
    $('menu').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-current',String(i===current)));
    const controls=$('controls');controls.replaceChildren();
    if(game.options)game.options.forEach((option,i)=>{const b=document.createElement('button');b.textContent=option;b.setAttribute('aria-pressed',String(value===i));b.onclick=()=>{value=i;render();$('controls').children[i].focus();};controls.append(b);});
    else{const label=document.createElement('label');const input=document.createElement('input');const output=document.createElement('output');input.type='range';input.min=game.range[0];input.max=game.range[1];input.value=value;input.setAttribute('aria-label',game.control);label.append(game.control,input,output);const update=()=>{value=Number(input.value);output.textContent=current===2?(value<0?'À esquerda':value>0?'À direita':'Central'):value+game.unit;scene();};input.addEventListener('input',update);controls.append(label);update();}
    scene();
  }
  function select(i){current=i;value=games[i].range?games[i].range[2]:0;revealed=false;document.querySelector('.scope').open=false;render();history.replaceState(null,'','#jogo-'+(i+1));}
  games.forEach((game,i)=>{const b=document.createElement('button');b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${game.name}`;b.onclick=()=>select(i);$('menu').append(b);});
  $('reveal').onclick=()=>{revealed=!revealed;render();};
  $('reset').onclick=()=>select(current);
  $('next').onclick=()=>{select((current+1)%games.length);$('game').scrollIntoView({block:'start'});};
  const initial=Number(location.hash.replace('#jogo-',''))-1;
  select(Number.isInteger(initial)&&initial>=0&&initial<10?initial:0);
})();
